language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip3 install coverage
install:
  - python3 setup.py install
script:
  - coverage run --source=airflowhdi -m unittest discover -s tests -v
after_success:
  - bash <(curl -s https://codecov.io/bash)